#
# Lta's zsh configuration
#

# Configure Antigen
if [ -f $HOME/.antigen/antigen.zsh ]; then
    ANTIGEN=$HOME/.antigen/antigen.zsh
fi

# Load Antigen
source $ANTIGEN

autoload -U colors && colors
setopt promptsubst

# Load the oh-my-zsh's library
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle common-aliases
antigen bundle git
antigen bundle gitfast
antigen bundle z

antigen bundle python
antigen bundle pip

export ATUIN_NOBIND="true"
antigen bundle atuinsh/atuin@main

antigen theme robbyrussell

# Local customizations, e.g. theme, plugins, aliases, etc.
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
[ -f "/workspace/$HF_USERNAME/repo/.zshrc.local" ] && \
    source "/workspace/$HF_USERNAME/repo/.zshrc.local"

# Tell Antigen that you're done
antigen apply

# We only want to bind Ctrl-R shortcut for atuin. So we disable it
# earlier, and now it's been loaded we bind the search
bindkey '^r' atuin-search

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"
